#!/usr/bin/env python

import clint
import ConfigParser
import json
import os
import requests
import sys

from clint.textui import colored

config = ConfigParser.ConfigParser()
config.read(os.path.expanduser('~/.snipt'))

username = config.get('user', 'username')
api_key = config.get('user', 'api_key')

reload(sys)
sys.setdefaultencoding('utf-8')


def main():

    # Post a new snipt.
    if clint.args.not_flags.get(0) == 'post_and_get_url':

        code = clint.piped_in()
        code = code.encode('utf-8')

        # Have a lexer? Let's use it.
        if clint.args.not_flags.get(1):
            lexer = clint.args.not_flags.get(1)
        else:
            lexer = 'text'

        data = {
            'code': code,
            'lexer': lexer,
            'title': 'Untitled'
        }

        if '-t' in clint.args.flags:
            data['tags'] = 'tmp'

        headers = {
            'Authorization': 'ApiKey {}:{}'.format(username, api_key),
            'Content-Type': 'application/json',
        }

        r = requests.post('https://snipt.net/api/private/snipt/',
                          data=json.dumps(data),
                          headers=headers)

        snipt_url = '{}?nice'.format(r.json()['raw_url'])

        if r.status_code in [200, 201]:
            sys.stdout.write(snipt_url)
        else:
            sys.stdout.write((colored.red("""Something wen't horribly wrong.
We got a non-OK response from Snipt.""")))

if __name__ == '__main__':
    main()
